### ISSUE TITLE
MOCKUP

### ISSUE THREAD

**Issue by edgarmauricio123** [SistemasTecTlaxiaco/actividad-10-mockup-de-aplicacion-web-3-equipo-daniel#2]
EN FIGMA:
https://www.figma.com/file/Cd893m1ze6ObOqCAQvdoZb/Untitled?node-id=0%3A1&t=JfSPTBqdlyXZY6q3-1
para ejecutar:
https://www.figma.com/proto/Cd893m1ze6ObOqCAQvdoZb/Untitled?page-id=0%3A1&node-id=1%3A5&viewport=434%2C-3054%2C0.5&scaling=min-zoom&starting-point-node-id=33%3A441

**Comment by josealfredo79** [comment]
Falto calificar

**Comment by josealfredo79** [comment]
Calificacion 43
